/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountForm: typeof import('./src/components/accounts/AccountForm.vue')['default']
    AccountSelector: typeof import('./src/components/common/AccountSelector.vue')['default']
    AggregatedStatsCard: typeof import('./src/components/apistats/AggregatedStatsCard.vue')['default']
    ApiKeyInput: typeof import('./src/components/apistats/ApiKeyInput.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    BatchApiKeyModal: typeof import('./src/components/apikeys/BatchApiKeyModal.vue')['default']
    BatchEditApiKeyModal: typeof import('./src/components/apikeys/BatchEditApiKeyModal.vue')['default']
    ChangeRoleModal: typeof import('./src/components/admin/ChangeRoleModal.vue')['default']
    ConfirmDialog: typeof import('./src/components/common/ConfirmDialog.vue')['default']
    ConfirmModal: typeof import('./src/components/common/ConfirmModal.vue')['default']
    CreateApiKeyModal: typeof import('./src/components/apikeys/CreateApiKeyModal.vue')['default']
    CustomDropdown: typeof import('./src/components/common/CustomDropdown.vue')['default']
    EditApiKeyModal: typeof import('./src/components/apikeys/EditApiKeyModal.vue')['default']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ExpiryEditModal: typeof import('./src/components/apikeys/ExpiryEditModal.vue')['default']
    GroupManagementModal: typeof import('./src/components/accounts/GroupManagementModal.vue')['default']
    LanguageSwitch: typeof import('./src/components/common/LanguageSwitch.vue')['default']
    LimitConfig: typeof import('./src/components/apistats/LimitConfig.vue')['default']
    LogoTitle: typeof import('./src/components/common/LogoTitle.vue')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    ModelDistribution: typeof import('./src/components/dashboard/ModelDistribution.vue')['default']
    ModelUsageStats: typeof import('./src/components/apistats/ModelUsageStats.vue')['default']
    NewApiKeyModal: typeof import('./src/components/apikeys/NewApiKeyModal.vue')['default']
    OAuthFlow: typeof import('./src/components/accounts/OAuthFlow.vue')['default']
    ProxyConfig: typeof import('./src/components/accounts/ProxyConfig.vue')['default']
    RenewApiKeyModal: typeof import('./src/components/apikeys/RenewApiKeyModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./src/components/common/StatCard.vue')['default']
    StatsOverview: typeof import('./src/components/apistats/StatsOverview.vue')['default']
    TabBar: typeof import('./src/components/layout/TabBar.vue')['default']
    ThemeToggle: typeof import('./src/components/common/ThemeToggle.vue')['default']
    ToastNotification: typeof import('./src/components/common/ToastNotification.vue')['default']
    TokenDistribution: typeof import('./src/components/apistats/TokenDistribution.vue')['default']
    UsageDetailModal: typeof import('./src/components/apikeys/UsageDetailModal.vue')['default']
    UsageTrend: typeof import('./src/components/dashboard/UsageTrend.vue')['default']
    UserApiKeysManager: typeof import('./src/components/user/UserApiKeysManager.vue')['default']
    UserUsageStats: typeof import('./src/components/user/UserUsageStats.vue')['default']
    UserUsageStatsModal: typeof import('./src/components/admin/UserUsageStatsModal.vue')['default']
    ViewApiKeyModal: typeof import('./src/components/user/ViewApiKeyModal.vue')['default']
    WindowCountdown: typeof import('./src/components/apikeys/WindowCountdown.vue')['default']
  }
}
